### ISSUE TITLE
Grinding noises during printing....

### ISSUE THREAD

**Issue by MSI-Promega** [PrintM3D/Promega#30]
New user. Have my printer running, but we hear grinding and squeaking noises and I have yet to isolate their location. Perhaps from the belt guide rollers...? Has anyone been experiencing this as well?

**Comment by jbolene** [comment]
yes I have the noises also

**Comment by tirelessirony** [comment]
I also have heard grinding noises. I picked up some compressed air and try to blow out the front and side idler pulleys every once in awhile. I think small bits of worn belt, dust, debris can get into the spaces between the smooth bearings and cause surprisingly loud grinding. 

That doesn't completely solve it, but between that and cleaning/lubricating rods and rails - I've heard less. I use PTFE lube on the rails and dry-film teflon on the rods.

**Comment by bass4aj** [comment]
I have encountered squeaking and grinding from 2 places: 1. is the front
idlers/bearings. The debris from the belt gets in the bearings. I just
replaced them with GT2 Idlers since they are more protected, but others
have soaked their bearings in kerosene and re lubricated them.
2. is the PTFE tubing for the filament. If it rubs along the x-gantry long
enough, it will start to screech.

**Comment by ericl-m3d** [comment]
Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related)
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw
- https://promega.printm3d.com/

Our support ticket is available at https://store.printm3d.com/pages/support 

-M3D Team
