### ISSUE TITLE
promega quad

### ISSUE THREAD

**Issue by jahreach** [PrintM3D/Promega#55]
there is no promega quad cura profile

**Comment by michaelarmani** [comment]
There is a base SD structure for the Mega Quad here:
https://github.com/PrintM3D/Promega/tree/devel/SD%20Card%20Structure/Quad

Building off of that, since Cura has no native quad mixing support, all quad/crane quad/mega quad users need to customize their open source applications to work with their system. For individual color swaps, you can teach Cura to treat each port as a different extruder.  Use the promega compound profile as a starting point.  Also look at the community mods https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/ such as the color mixing post-processor made by sindarius
